export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';


export const LOGIN_REQUEST= 'LOGIN_REQUEST';
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const LOGIN_FAILURE= 'LOGIN_FAILURE';
export const LOGOUT_REQUEST= 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS';

export const ADD_FEEDBACK= 'ADD_FEEDBACK';
export const DELETE_FEEDBACK= 'DELETE_FEEDBACK';
export const FEEDBACK_FAILED= 'FEEDBACK_FAILED';
